server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: agenda
        uri: lb://agenda
        predicates:
        - Path=/agenda/**
      - id: funcionario
        uri: lb://funcionario
        predicates:
        - Path=/aluno/**
      - id: sala
        uri: lb://sala
        predicates:
        - Path=/sala/**
eureka:
  instance:
    hostname: register
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.30.6.14:8761/eureka
