global:
  scrape_interval: 15s
  scrape_timeout: 5s

scrape_configs:
  - job_name: "agenda"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["172.30.13.97:8080"]
        labels:
          application: "agenda"
