server:
  port: 8761
eureka:
  instance:
    hostname: register
    health-check-url: http://localhost:8761/eureka/app
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    renewal-percent-threshold: 0.33
